FROM quay.io/buildah/stable:v1.21.0
LABEL maintainers="David Festal"
LABEL description="Software Catalogs Adapter"

COPY ./bin/softwarecatalogsadapter /softwarecatalogsadapter
ENTRYPOINT ["/softwarecatalogsadapter"]
