kind: Deployment
apiVersion: apps/v1
metadata:
  name: example
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scratch-with-bash-core-utils
  template:
    metadata:
      labels:
        app: scratch-with-bash-core-utils
    spec:
      containers:
        - name: scratch
          image: 'docker.io/resin/scratch:latest'
          command:
            - /bin/bash
            - '-c'
            - tail -f
          env:
            - name: PATH
              value: /bin
          volumeMounts:
            - name: my-shell
              mountPath: /bin
      volumes:
        - name: my-shell
          csi:
            driver: toolprovider.csi.katalogos.dev
            volumeAttributes:
              image: 'quay.io/dfestal/csi-tool-bash-coreutils:latest'
